- name: Install prerequisites
  hosts: all
  strategy: free
  become: true
  become_method: sudo
  tasks:
    - name: Ubuntu - install sshfs
      apt:
        name:
          - sshfs
        state: present
        update_cache: yes
      register: apt_res
      retries: 3
      until: apt_res is success
      when: ansible_distribution == 'Ubuntu'
    - name: RedHat - install dnf requirements
      yum:
        name:
          - epel-release
          - dnf
          - python-dnf
        state: present
        update_cache: yes
      when: ansible_os_family == 'RedHat'
    - name: RedHat -  install sshfs
      dnf:
        name: fuse-sshfs
        enablerepo: PowerTools
        state: present
      when: ansible_os_family == 'RedHat'
    - name: Debian - install sshfs
      apt:
        name:
          - sshfs
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'
